apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  namespace: sujith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      imagePullSecrets:
        - name: artifact-secret   # <-- IMPORTANT (ADD THIS)
      containers:
        - name: spring-petclinic
          image: {{.Values.image}}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  selector:
     app: spring-petclinic
  type: NodePort
  ports:
  - targetPort: 8080
    port: 80
    protocol: "TCP"
  
    
